Add FormKeep email capture for pre-launch
Workflow:

* User enters email address.
* Data goes to FormKeep, which checks for spam.
* FormKeep forwards email address to HubSpot.
* HubSpot drip email campaign starts.
* Add form styling! Zing!

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -2,14 +2,12 @@
 
 # Run this script immediately after cloning the codebase.
 
-# Make sure Bundler is installed
-if [ `gem query -i -n bundler` = "false" ]; then
-  echo -e "Installing Bundler..."
-  gem install bundler
-fi
+# Exit if any subcommand fails
+set -e
 
-# Set up Ruby dependencies via Bundler
-echo -e "Installing Dependencies..."
+# Set up Ruby dependencies
+gem install bundler --conservative
 bundle check || bundle install
 
+# Add binstubs to PATH via export PATH=".git/safe/../../bin:$PATH" in ~/.zshenv
 mkdir -p .git/safe
